# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: f634156
_src_path: gh:YukkuriC/hexdoc-hexcasting-template
author: YukkuriC
book_id: hexcasting:thehexbook
default_branch: main
github_repo: HexArsLinker
gradle_mod_version_key: mod_version_base
hexdoc_mod_plugin_classname: HexArsLinkerModPlugin
hexdoc_plugin_classname: HexArsLinkerPlugin
java_lang:
    ext: java
    src: java
java_package: io/yukkuric/hex_ars_link
mod_display_name: Hex-Ars Linker
modid: hex_ars_link
multiloader: false
package_export_root: doc/src/hexdoc_hex_ars_link/_export
package_name: hexdoc-hex-ars-link
package_slug: hexdoc_hex_ars_link
package_src: doc/src/hexdoc_hex_ars_link
pages_url: https://yukkuric.github.io/HexArsLinker/
pattern_regex:
    per_world_value: 'true'
    regex: wrap\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)
pattern_registry: action/HexArsActions.kt
